export const PRODUCT_COPY = {
  name: "QuizFlow AI",
  tagline: "AI Funnel Builder for Paid Social Ads",
  hero: {
    badge: "AI Funnel Builder for Paid Social Ads",
    headline: "Build High-Converting AI Funnels for TikTok, Facebook and Instagram Ads",
    subhead:
      "Choose your funnel type. AI builds the full experience — questions, results, and lead capture — optimized for paid social campaigns.",
    funnelPickerHeading: "What would you like to build?",
    funnelPickerSubhead: "One platform. Four funnel strategies. All powered by the same AI engine.",
    primaryCta: "Create your first funnel",
    secondaryCta: "See how it works",
  },
  app: {
    homeHeadline: "What would you like to build today?",
    homeSubhead: "Choose a funnel type to start building.",
    createTitle: "Create funnel",
    createDescription: "Describe your offer and audience — AI drafts the full funnel.",
    funnelsTitle: "My Funnels",
    funnelsDescription: "Edit, publish, or create another funnel.",
    settingsTitle: "Settings",
    settingsDescription: "Account and workspace preferences.",
    billingTitle: "Billing",
    billingDescription: "Plan, payment method, and invoices.",
  },
  funnel: {
    create: "Create Funnel",
    generate: "Generate Funnel",
    myFunnels: "My Funnels",
    builder: "Funnel Builder",
    new: "New Funnel",
    saved: "Saved Funnels",
    generator: "Funnel Generator",
  },
} as const;
